language: r
sudo: false
cache: packages
warnings_are_errors: false

r_binary_packages:
  - devtools
  - roxygen2

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'devtools::install();devtools::test()'
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
